version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - ./src:/src/
    env_file:
      - ./src/.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16-alpine
    container_name: db
    volumes:
      - dev-database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=changeme
  
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  dev-database:
  redis-data: